services:
  minio:
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    restart: always
    ports:
      - 9000:9000 # Storage
      - 9001:9001 # Console
    env_file:
      - .env
    volumes:
      - minio:/data
    entrypoint: []
    command: minio server /data --address :9000 --console-address :9001
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s

  mc:
    image: minio/mc:RELEASE.2023-08-18T21-57-55Z
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: []
    command: |
      sh -c "
        mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD
        mc mb myminio/$$S3_BUCKET --region=$$S3_REGION || true
        mc mb myminio/$$TEST_S3_BUCKET --region=$$S3_REGION || true
      "

volumes:
  minio:
    driver: local
